
pcm.!default {
    pcm "hw:0,0"    
}

pcm.dmicQBO {
    type hw
    card sndrpisimplecar
    channels 2
    rate 16000
    format S16_LE
}

pcm.dmicQBO_sv {
    type softvol
    slave.pcm dmicQBO
    control {
        name "Boost Capture Volume"
        card sndrpisimplecar
    }
    min_dB -10.0
    max_dB 30.0
}

pcm_slave.sl1 {
    pcm "hw:0,0"
    channels 2
    rate 16000
    format S16_LE
}

pcm.convertQBO {
    type plug
    slave sl1
}

